jobs:
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  services:
    redis:
      image: redis
      ports:
      - 6379:6379
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.101'
  - script: cd singlecp && bash deploy_aelf.sh
    displayName: 'Deploy a full node'
  - script: bash build.sh -target=test
    displayName: 'build and test'
